imports:
    - { resource: config.yml }

parameters:
    redbean:
        default:
            type: "%database_type%"
            host: "%database_host%"
            port: "%database_port%"
            name: "%database_name%"
            user: "%database_user%"
            password: "%database_password%"
            env: "%database_env%"
            frozen: false
    recaptcha:
        sitekey:       6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI
        secretkey:     6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe
        api:           https://www.google.com/recaptcha/api.js
        session_var:   'hasCompletedCaptcha'
framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: [!event]
        console:
            type:   console
            channels: [!event, !doctrine]
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type:   firephp
        #    level:  info
        #chromephp:
        #    type:   chromephp
        #    level:  info

swiftmailer:
    default_mailer: spooled
    mailers:
        spooled:
            transport: "%mailer_transport%"
            host:      "%mailer_host%"
            username:  "%mailer_user%"
            password:  "%mailer_password%"
            port:       587
            encryption: tls
            auth_mode: login
            delivery_address: lapidary@windstream.net
            spool:
                type: file
                path: "%kernel.root_dir%/../var/spool"
        delayed:
            transport: "%mailer_transport%"
            host:      "%mailer_host%"
            username:  "%mailer_user%"
            password:  "%mailer_password%"
            port:       587
            encryption: tls
            auth_mode: login
            delivery_address: lapidary@windstream.net
            spool:
                type: file
                path: "%kernel.root_dir%/../var/spool"
        instant:
            transport: "%mailer_transport%"
            host:      "%mailer_host%"
            username:  "%mailer_user%"
            password:  "%mailer_password%"
            port:       587
            encryption: tls
            auth_mode: login
            delivery_address: lapidary@windstream.net
            spool:
                type: file
                path: "%kernel.root_dir%/../var/spool"